### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by wanliyunyan** [aimalygin/LibXray#2]
this is my project [xray_ios](https://github.com/wanliyunyan/xray_ios)，Please help me.
I’m in big trouble. I want to debug NEPacketTunnelProvider, but no matter what I do, the `print` I write in this class don’t log anything to the console. What should I do to make the logs appear in the console?  
This iOS application runs perfectly on the phone.

**Comment by aimalygin** [comment]
Do you run the app or the tunnel extension via xcode?

**Comment by wanliyunyan** [comment]
app

**Comment by wanliyunyan** [comment]
I got it. When I run the app, the tunnel doesn’t log anything to the console unless the tunnel is actively running. However, my ultimate goal is to build a Flutter project, and in a Flutter project, I can’t directly run and debug the tunnel. Is there any solution for this?

**Comment by wanliyunyan** [comment]
`
    func start() async throws {
        try manager?.connection.startVPNTunnel()
    }
`
In iOS, when this line of code is executed, the PacketTunnelProvider class is automatically triggered. In Flutter, will this class also be automatically triggered?
`
class PacketTunnelProvider: NEPacketTunnelProvider {

    // 开始隧道的方法，会在创建隧道时调用
    override func startTunnel(options: [String : NSObject]? = nil) async throws {
`
